server:
  port: 8000
  servlet:
    context-path: /blog
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource: # db 설정.
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa:
    open-in-view: true #Lazy 로딩이 가능해짐. false 일 경우 영속성 컨텍스트의 시작 시점이 Cotroller에서 Service 단으로 내려간다.
    hibernate:
      ddl-auto: update #첫 시작에만 create 해야 한다. 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Entity를 만들때 변수명 그대로 테이블에 넣어준다.
      use-new-id-generator-mappings: false # jpa의 기본 전략을 따라갈지 여부. 
    show-sql: true # 콘솔에 sql의 표시 여부.
    properties:
      hibernate.format_sql: true # 이거 안하면 sql문이 한줄로 길~게 나옴. 가독성이 좋아진다!

  jackson:
    serialization:
      fail-on-empty-beans: false